### ISSUE TITLE
Leveraging Safelist

### ISSUE THREAD

**Issue by cccs-rs** [CybercentreCanada/assemblyline-service-extract#39]
Reference: https://discordapp.com/channels/908084610158714900/908717441771794472/951476535842451486

Use the system's safelist to limit the number of files extracted and added to a submission. This will help minimize the MAX_EXTRACT_DEPTH concerns and focus on analyzing files that we haven't seen before.

**Comment by foxalfabravo** [comment]
In a first step,  jar_whitelisting function could be under the control of a service parameter (check_whitelist, default:true) , so that an analyst could force the extraction of whatever checks in this long list of exceptions. 
The building of the safelist could also be performed by a "clean for the moment" automated collector, with or without human vetting

**Comment by cccs-rs** [comment]
Well I'm thinking of the leveraging the AL safelist on all extract methods to avoid appending files that are known to be safe, this will support the triage-focused use-case.

However, if an analyst wants to know the complete unfiltered results from Extract (or the rest of the system), I think this is where a `deep_scan` flag could come into play and disable safelisting.

**Comment by foxalfabravo** [comment]
I don't understand why you keep the whitelisting code just above [270-272] as those files could be check against the safelist also. I understand it lowers the number of files to handle, but the system may miss hidden stuff in an image.

**Comment by cccs-rs** [comment]
To be honest, I didn't even know Extract had whitelisting methods in it's code for special cases, this could be a configurable flag like you suggested: `use_custom_safelisting: true (default)`
